import { useState } from "react";
import "./conta.css";
function Conta({ inicio, explorar, favoritos, painel, email = "", tipoConta = "cliente", login, cadastro }) {
  const [nome, setNome] = useState("");
  const [mensagem, setMensagem] = useState("");
  const [editando, setEditando] = useState(false);
  return <div className="account-page"><nav className="account-navbar"><button className="brand-mark" onClick={inicio}>Vitrine<span>.</span></button><div className="collection-links"><button onClick={inicio}>Início</button><button onClick={explorar}>Explorar</button><button onClick={favoritos}>Favoritos</button><button className="current">Minha conta</button></div></nav><main className="account-content"><button className="collection-back" onClick={inicio}>← Voltar ao início</button><span className="eyebrow"><span className="eyebrow-dot"/> ÁREA PESSOAL</span><h1>Minha <span>conta.</span></h1><p className="account-lead">Consulte seus dados e acesse os recursos do Vitrine.</p><section className="account-profile-card"><div className="account-avatar">{(nome||email||"V").slice(0,1).toUpperCase()}</div><div className="account-profile-info"><span className="account-label">PERFIL {tipoConta==="empreendedor"?"EMPREENDEDOR":"CLIENTE"}</span><h2>{nome||"Olá, seja bem-vindo!"}</h2><p>{email||"Você ainda não entrou com uma conta cadastrada."}</p></div><button className="button-outline" onClick={()=>setEditando(!editando)}>{editando?"Cancelar":"Editar nome"}</button></section>{editando&&<form className="account-edit" onSubmit={(e)=>{e.preventDefault();setEditando(false);setMensagem("Nome atualizado nesta demonstração.");}}><label>Nome de exibição<input value={nome} onChange={(e)=>setNome(e.target.value)} placeholder="Digite seu nome" required/></label><button className="button-light" type="submit">Salvar nome ↗</button></form>}{mensagem&&<p className="account-message" role="status">{mensagem}</p>}<div className="account-shortcuts"><button onClick={explorar}><span>⌕</span><strong>Explorar negócios</strong><small>Encontre empresas e serviços na sua região.</small><b>↗</b></button><button onClick={favoritos}><span>♡</span><strong>Meus favoritos</strong><small>Acesse os negócios que você guardou.</small><b>↗</b></button>{tipoConta==="empreendedor"&&<button onClick={painel}><span>▦</span><strong>Painel da empresa</strong><small>Gerencie perfil, catálogo e preferências.</small><b>↗</b></button>}</div>{!email&&<section className="account-signin"><h2>Entre para aproveitar o Vitrine</h2><p>Crie uma conta para usar os recursos personalizados da plataforma.</p><div><button className="button-light" onClick={login}>Fazer login</button><button className="button-outline" onClick={cadastro}>Criar conta</button></div></section>}<p className="account-note">A autenticação e o armazenamento definitivo dos dados serão habilitados após a integração da API de usuários.</p></main></div>;
}
export default Conta;
