import { useState } from "react";
import "./perfilEmpresa.css";
function PerfilEmpresa({ voltar, explorar, inicio, favoritos = [], alternarFavorito, empresa }) {
  const [mensagem, setMensagem] = useState("");
  const nome = empresa?.nome || (typeof empresa === "string" ? empresa : "Empresa local");
  const categoria = empresa?.categoria?.nome || "Categoria não informada";
  const cidade = empresa?.cidade?.nome || "Localização não informada";
  const estado = empresa?.cidade?.estado?.sigla ? `, ${empresa.cidade.estado.sigla}` : "";
  const descricao = empresa?.descricao || "Conheça os produtos e serviços oferecidos por esta empresa. Entre em contato para saber mais sobre o que ela oferece.";
  const favorita = favoritos.some((item)=>(item?.id??item?.nome??item)===(empresa?.id??empresa?.nome??empresa));
  return <div className="perfil-page"><nav className="perfil-navbar"><button className="brand-mark" onClick={inicio}>Vitrine<span>.</span></button><div className="perfil-nav-links"><button onClick={inicio}>Início</button><button onClick={explorar}>Explorar</button><button onClick={voltar}>Resultados</button></div></nav>
    <main className="perfil-content"><button className="profile-back" onClick={voltar}>← Voltar para empresas</button><section className="empresa-profile"><div className="empresa-cover"><span>V.</span><div className="cover-label">NEGÓCIO LOCAL</div></div><div className="empresa-profile-info"><div><span className="business-category">{categoria} · {cidade}{estado}</span><h1>{nome}</h1><p>{descricao}</p></div><button className={favorita?"favorite-button is-favorite":"favorite-button"} onClick={()=>{alternarFavorito?.(empresa||{nome});setMensagem(favorita?"Empresa removida dos favoritos.":"Empresa adicionada aos favoritos.");}}>{favorita?"♥ Favoritado":"♡ Favoritar"}</button></div><div className="empresa-meta"><span><b>⌖</b> {cidade}{estado}</span><span><b>☆</b> Avaliações ainda não disponíveis</span><span><b>▤</b> Catálogo da empresa</span></div></section>{mensagem&&<p className="profile-message" role="status">{mensagem}</p>}
      <section className="catalog-section"><div className="profile-section-heading"><div><h2>Produtos e serviços</h2><p>Conheça o que esta empresa oferece.</p></div><span className="profile-count">CATÁLOGO</span></div><div className="profile-empty"><span>▤</span><h3>O catálogo será exibido aqui</h3><p>Os produtos e serviços ainda não estão conectados à API. Quando essa parte do back-end estiver pronta, os itens cadastrados pela empresa aparecerão nesta área.</p></div></section>
      <section className="reviews-section"><div className="profile-section-heading"><div><h2>Avaliações</h2><p>As experiências ajudam outras pessoas a descobrir bons negócios.</p></div></div><div className="profile-empty review-empty"><span>☆</span><h3>Avaliações em breve</h3><p>O cadastro e a consulta de avaliações ainda precisam ser integrados ao back-end. Conforme as regras do projeto, será necessário entrar em uma conta para avaliar uma empresa.</p><button className="button-outline" onClick={()=>setMensagem("A função de avaliação será habilitada após a integração com a API de usuários e avaliações.")}>Como avaliar?</button></div></section>
      <div className="profile-bottom-cta"><div><h2>Gostou deste negócio?</h2><p>Guarde o perfil para encontrar de novo quando quiser.</p></div><button className="button-light" onClick={()=>{alternarFavorito?.(empresa||{nome});setMensagem(favorita?"Empresa removida dos favoritos.":"Empresa adicionada aos favoritos.");}}>{favorita?"♥ Salvo nos favoritos":"♡ Adicionar aos favoritos"}</button></div>
    </main></div>;
}
export default PerfilEmpresa;
